### ISSUE TITLE
Division by 0 if all data in histogram is in over/underflow bins

### ISSUE THREAD

**Issue by wecassidy** [zctao/omnifoldTop#20]
Minimum example:
```python
>>> data = [10]
>>> bins = [0, 10]
>>> histogramming.calc_hist(data, bins)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wcassidy/wd_of/python/histogramming.py", line 72, in calc_hist
    check_hist_flow(h)
  File "/home/wcassidy/wd_of/python/histogramming.py", line 44, in check_hist_flow
    if float(n_underflow/n_total) > threshold_underflow:
ZeroDivisionError: float division by zero
```

The relevant function is histogramming.check_hist_flow():
```python
def check_hist_flow(h, threshold_underflow=0.01, threshold_overflow=0.01):
    n_underflow = h[hist.underflow]['value']
    n_overflow = h[hist.overflow]['value']
    n_total = h.sum()['value']

    if float(n_underflow/n_total) > threshold_underflow:
        logger.debug("Percentage of entries in the underflow bin: {}".format(float(n_underflow/n_total)))
        logger.warn("Number of entries in the underflow bin exceeds the threshold!")
        return False

    if float(n_overflow/n_total) > threshold_overflow:
        logger.debug("Percentage of entries in the overflow bin: {}".format(float(n_overflow/n_total)))
        logger.warn("Number of entries in the overflow bin exceeds the threshold!")
        return False

    return True
```

There's a zero division error when all the data is in over/underflow bins since `hist.hist.Hist.sum` doesn't include over/underflow bins unless it is passed the argument `flow=True`. There are two potential fixes that I see:
1. Pass `flow=True` to `h.sum`. This slightly changes how the overflow and underflow percentages are calculated by changing the denominator from "number of non-over/underflow datapoints" to "number of datapoints, including over and underflow".
2. Check for the `n_total == 0` case and handle it specially, preserving the current behaviour.

Any preferences for which way to go? I'd prefer option 1 unless it's important to maintain the current behaviour.

**Comment by zctao** [comment]
Option 1 looks good to me too.
